Planck_SMICA
ellmin = 30, ellmax = 3000, delta_L = 150
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Planck_SMICA
ellmin = 30, ellmax = 4000, delta_L = 200
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

CMB_S3
ellmin = 30, ellmax = 3000, delta_L = 150
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

CMB_S3
ellmin = 30, ellmax = 4000, delta_L = 200
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

CMB_S4
ellmin = 30, ellmax = 3000, delta_L = 150
reading in CMB map
CMB_S4
ellmin = 30, ellmax = 4000, delta_L = 200
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

reference
ellmin = 30, ellmax = 3000, delta_L = 150
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

reference
ellmin = 30, ellmax = 4000, delta_L = 200
reading in CMB map
Traceback (most recent call last):
  File "../new_sims.py", line 78, in <module>
    cmb_alm = hp.read_alm(map_path + 'lensed_cmb_alm.fits', hdu=1)
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in read_alm
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 604, in <listcomp>
    idx, almr, almi = [_get_hdu(filename, hdu=unit).data.field(i) for i in range(3)]
  File "/global/homes/h/hongbo/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/healpy/fitsfunc.py", line 657, in _get_hdu
    hdulist = pf.open(input_data, memmap=memmap)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1046, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/homes/h/hongbo/.conda/envs/myenv/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'maps/Colin/lensed_cmb_alm.fits'

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

